spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1030707742527-ai4fj55uob9s20gc4h68rnqtv6i22n4o.apps.googleusercontent.com
            client-secret: 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
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

app:
  cors:
    maxAgeSecs: 3600
    allowedOrigins:
      - http://localhost:3000
  oauth2:
    redirectUri: "http://localhost:3000/"
  img:
    uploadDirectory: "./src/main/resources/images"
