spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SBERMARKET_MANAGER_POSTGRES_URL}
    username: ${SBERMARKET_MANAGER_POSTGRES_USERNAME}
    password: ${SBERMARKET_MANAGER_POSTGRES_PASSWORD}

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate