spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1030707742527-ai4fj55uob9s20gc4h68rnqtv6i22n4o.apps.googleusercontent.com
            client-secret: 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

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

app:
  cors:
    maxAgeSecs: 3600
    allowedOrigins:
      - http://localhost:3000
  oauth2:
    redirectUri: "http://localhost:3000/"